package com.cqupt.domain;
// default package
// Generated 2015-12-17 16:48:17 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.cqupt.common.BaseEntity;
/**
 * Educate generated by hbm2java
 */
public class Educate extends BaseEntity{
	/**
	 * 
	 */
	private static final long serialVersionUID = 2107664419977180335L;
	private String id;
	private String name;//这个是培训名称
	private String purpose;
	private Date begintime;
	private Date endtime;
	private String datum;
	private String teacher;
	private Date createtime;
	private String effect;
	private String summarize;
	private Set<Job> jobs=new HashSet<Job>();
	private Set<Users> users=new HashSet<Users>();

	public Set<Users> getUsers() {
		return users;
	}

	public void setUsers(Set<Users> users) {
		this.users = users;
	}

	
	public Set<Job> getJobs() {
		return jobs;
	}

	public void setJobs(Set<Job> jobs) {
		this.jobs = jobs;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public Date getBegintime() {
		return this.begintime;
	}

	public void setBegintime(Date begintime) {
		this.begintime = begintime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public String getDatum() {
		return this.datum;
	}

	public void setDatum(String datum) {
		this.datum = datum;
	}

	public String getTeacher() {
		return this.teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getEffect() {
		return this.effect;
	}

	public void setEffect(String effect) {
		this.effect = effect;
	}

	public String getSummarize() {
		return this.summarize;
	}

	public void setSummarize(String summarize) {
		this.summarize = summarize;
	}

	public Educate saveEducate() {
		// TODO Auto-generated method stub
		return null;
	}

}
