package com.cqupt.domain;
// default package
// Generated 2015-12-17 16:48:17 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import com.cqupt.common.BaseEntity;

/**
 * Institution generated by hbm2java
 */
public class Institution extends BaseEntity{

	/**
	 * 
	 */
	private static final long serialVersionUID = -6506938346449518387L;
	private String id;
	private String name;//这个是工号
	private String explains;
	private Date createtime;
	private Float money;
	private Users user;

	private Byte typeFlag;

	

	

	public Byte getTypeFlag() {
		return typeFlag;
	}

	public void setTypeFlag(Byte typeFlag) {
		this.typeFlag = typeFlag;
	}

	public Float getMoney() {
		return money;
	}

	public void setMoney(Float money) {
		this.money = money;
	}

	public Users getUser() {
		return user;
	}

	public void setUser(Users user) {
		this.user = user;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getExplains() {
		return this.explains;
	}

	public void setExplains(String explains) {
		this.explains = explains;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

}
