package com.cqupt.domain;
// default package
// Generated 2015-12-17 16:48:17 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.cqupt.common.BaseEntity;

/**
 * Job generated by hbm2java
 */
public class Job extends BaseEntity{

	/**
	 * 
	 */
	private static final long serialVersionUID = -5102132298638103038L;
	private String id;
	private String name;//这个是工号
	private Date createtime;
	private String content;
	private Byte jobtype;
	private Set<Educate> edus=new HashSet<Educate>();
    private Set<Users> users;
	


	public Byte getJobtype() {
		return jobtype;
	}

	public void setJobtype(Byte jobtype) {
		this.jobtype = jobtype;
	}

	public Set<Educate> getEdus() {
		return edus;
	}

	public void setEdus(Set<Educate> edus) {
		this.edus = edus;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Set<Users> getUsers() {
		return users;
	}

	public void setUsers(Set<Users> users) {
		this.users = users;
	}

	
	

}
