package com.cqupt.domain;
// default package
// Generated 2015-12-17 16:48:17 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.Set;

import com.cqupt.common.BaseEntity;

/**
 * Users generated by hbm2java
 */
public class Users extends BaseEntity{

	/**
	 * 
	 */
	private static final long serialVersionUID = -5494682522407728505L;
	private String id;
	private String username;//这个是工号！
	private String password;
	private String realname;//这个才是姓名
	private Byte worktype;
	private Byte sex;
	private Date birthday;
	private Date createtime;
	private Date logintime;
	private Date logouttime;
	private Byte isadmin=0;
	private String content;
	private Set<Stipend> sts;
	private Set<Institution> inss;
	private Job job;
	private String jobname;
	private Byte userPic;



	public Byte getUserPic() {
		return userPic;
	}

	public void setUserPic(Byte userPic) {
		this.userPic = userPic;
	}

	public Date getLogintime() {
		return logintime;
	}

	public void setLogintime(Date logintime) {
		this.logintime = logintime;
	}

	public Date getLogouttime() {
		return logouttime;
	}

	public void setLogouttime(Date logouttime) {
		this.logouttime = logouttime;
	}

	public Byte getWorktype() {
		return worktype;
	}

	public void setWorktype(Byte worktype) {
		this.worktype = worktype;
	}

	public String getJobname() {
		return jobname;
	}

	public void setJobname(String jobname) {
		this.jobname = jobname;
	}

	public Set<Stipend> getSts() {
		return sts;
	}

	public void setSts(Set<Stipend> sts) {
		this.sts = sts;
	}

	public Set<Institution> getInss() {
		return inss;
	}

	public void setInss(Set<Institution> inss) {
		this.inss = inss;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	
	public Job getJob() {
		return job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Byte getSex() {
		return this.sex;
	}

	public void setSex(Byte sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Byte getIsadmin() {
		return this.isadmin;
	}

	public void setIsadmin(Byte isadmin) {
		this.isadmin = isadmin;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

    
	
    
}
